# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0002_auto_20190613_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('details', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='mygallery.tags')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mygallery.Uploader')),
            ],
        ),
    ]
