# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0003_pdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploader',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
